= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению не предъявляются.

[#software]
== Необходимое программное обеспечение

.*Модули {dv}*:
. Серверная и клиентская части модуля _{dv} 5. {pl}_ версии {pl-req} и выше.
. Серверная и клиентская части приложения _{dv} 5. {dm}_ версии {dm-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {wf}_ версии {wf-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {ad}_ версии {ad-req} и выше.
. Серверная и клиентская части приложения _{dv} 5. {to}_ версии {to-req} и выше.
. Серверная и клиентская части модуля _{dv} 5. {wincl}_ версии {win-req} и выше.

[#database]
== Требования к базе данных

Модулю репликации справочников требуется БД для хранения настроек и оперативных данных. БД может работать под управлением СУБД Microsoft SQL Server 2014 и выше.

WARNING: Работа с системой {dv} с БД PostgreSQL не поддерживается.

Данная версия модуля не совместима с {dv} версии 5.4.

[#network]
== Требования к каналам связи

Администратор должен обеспечить возможность передачи данных по локальной сети между серверами {dv}, участвующими в межфилиальном обмене.

На сервере-публикаторе в момент синхронизации должен быть обеспечен прямой сетевой доступ к {dv} всех серверов-подписчиков.

[#license]
== Лицензия

Для работы с модулем _{dv} 5. Модуль репликации справочников_ лицензия на систему {dv} должна содержать одну или обе дополнительные опции:

* _{dv} Directory Replicator (Publisher Service)_ -- для сервера-публикатора.
* _{dv} Directory Replicator (Recipient Agent)_ -- для сервера-подписчик.

Лицензионная опция должна быть у каждого сервера {dv}, участвующего в репликации.
