[[ariaid-title1]]
== Разрешение конфликтов

При синхронизации данных на разных серверах могут возникать конфликты, связанные с тем, что на разных площадках в одни и те же данные вносятся разные изменения в рамках одного цикла синхронизации.

Данные конфликты должны быть решены на уровне установки соответствующих прав на данные, участвующие в синхронизации. Например, можно установить запрет на редактирование конкретного справочника пользователям подчиненного филиала, работающим в системе на территориально удаленном сервере.

Кроме этого, система Docsvision поддерживает механизм разграничения прав доступа в зависимости от того, какой из серверов является владельцем той или иной записи:

* если в схеме карточки для секции установлен признак «Не редактировать строки с иного сервера», то изменить запись можно только на том сервере, на котором эта запись была создана;
* если в схеме карточки для секции установлен признак «Не изменять дочерние строки с иного сервера», то добавить или изменить подчиненные строки можно только на том сервере, на котором эта запись была создана.

Информация о том, на каком сервере была создана запись, хранится в служебном поле любой секции «OwnerServerID». Для смены владельца записи необходимо заменить идентификатор в данном поле на идентификатор того сервера, который должен стать владельцем записи.

*На уровень выше:* xref:../topics/Structure.adoc[Архитектура модуля]
