[[ariaid-title1]]
== Установка Сервиса репликации справочников

Сервис репликации справочников представляет собой службу Windows, запускаемую от имени пользователя, указанного при xref:CreateProfile.adoc[создании профиля подключения]. После установки Сервиса репликации справочников учётную запись можно изменить только в настройках службы Windows.

Сервис репликации можно установить двумя способами:

. Из командной строки:
[loweralpha]
.. Запустите командную строку от имени администратора.
.. Перейдите в папку [.ph .filepath]`C:\Program Files (x86)\Docsvision\DirectoryReplication\5.5\Lib\` (каталог установки Модуля репликации справочников).
.. Выполните команду: `DocsVision.DirectoryReplication.Service.exe /i «Название                 профиля подключения»`. Например: `DocsVision.DirectoryReplication.Service.exe /i Standard`.
+
В Windows будет зарегистрирована служба с названием «DvDistrService <Название профиля подключения>» (отображаемое имя – «Docsvision Сервис репликации справочников <Название профиля подключения>»).
+
Запустите созданную службу командой `sc start "DvDistrService <Название профиля               подключения>"`.
+
Сервис репликации работает только с одним подключением. Если в «Консоли настроек репликации справочников Docsvision» зарегистрировано несколько профилей подключения – последовательно установите сервис репликации с каждым из профилей.
. С помощью «Консоли настроек репликации справочников Docsvision»:
[loweralpha]
.. Запустите программу «Консоль настроек репликации справочников Docsvision» из меню Пуск от имени локального администратора.
.. Выберите профиль подключения с БД Docsvision, который будет использоваться при запуске сервиса репликации.
.. Нажмите кнопку [.ph .uicontrol]*Подключиться*. Будет открыто окно настройки сценариев обмена.
.. Нажмите кнопку [.ph .uicontrol]*Запустить сервис синхронизации*/[.ph .uicontrol]*Установить сервис синхронизации*. В Windows будет зарегистрирована служба с названием «DvDistrService <Название профиля подключения>».
.. Нажмите кнопку [.ph .uicontrol]*Перезапустить сервис* для запуска созданной службы.

При необходимости, удалить сервис репликации можно средствами ОС Windows или командой `DocsVision.DirectoryReplication.Service.exe /u <Название профиля         подключения>`.

*На уровень выше:* xref:../topics/HowConfig.adoc[Подготовка к работе]
