= Установка Сервиса репликации справочников

Сервис репликации справочников представляет собой службу Windows, запускаемую от имени пользователя, указанного при xref:CreateProfile.adoc[создании профиля подключения]. После установки Сервиса репликации справочников учётную запись можно изменить только в настройках службы Windows.

Сервис репликации можно установить двумя способами:

. Из командной строки:
[loweralpha]
.. Запустите командную строку от имени администратора.
.. Перейдите в папку `C:\Program Files (x86)\{dv}\DirectoryReplication\5.5\Lib\` (каталог установки Модуля репликации справочников).
.. Выполните команду: `{dv}.DirectoryReplication.Service.exe /i "Название                 профиля подключения"`. Например: `{dv}.DirectoryReplication.Service.exe /i Standard`.
+
В Windows будет зарегистрирована служба с названием "DvDistrService <Название профиля подключения>" (отображаемое имя -- "{dv} Сервис репликации справочников <Название профиля подключения>").
+
Запустите созданную службу командой `sc start "DvDistrService <Название профиля               подключения>"`.
+
Сервис репликации работает только с одним подключением. Если в "Консоли настроек репликации справочников {dv}" зарегистрировано несколько профилей подключения -- последовательно установите сервис репликации с каждым из профилей.
. С помощью "Консоли настроек репликации справочников {dv}":
[loweralpha]
.. Запустите программу "Консоль настроек репликации справочников {dv}" из меню Пуск от имени локального администратора.
.. Выберите профиль подключения с БД {dv}, который будет использоваться при запуске сервиса репликации.
.. Нажмите кнопку *Подключиться*. Будет открыто окно настройки сценариев обмена.
.. Нажмите кнопку *Запустить сервис синхронизации*/*Установить сервис синхронизации*. В Windows будет зарегистрирована служба с названием "DvDistrService <Название профиля подключения>".
.. Нажмите кнопку *Перезапустить сервис* для запуска созданной службы.

При необходимости, удалить сервис репликации можно средствами ОС Windows или командой `{dv}.DirectoryReplication.Service.exe /u <Название профиля         подключения>`.
